language: php
php:
  - 5.5
  - 5.4

services:
  - memcached

before_install:
  - phpenv config-add tests/memcache.ini
  - sudo apt-get update -qq
  - sudo apt-add-repository -y ppa:phalcon/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-phalcon

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: ZEND_DONT_UNLOAD_MODULES=1 $(phpenv which php) ./tests/Falconer/ci/phpunit.php --debug -c tests/Falconer/phpunit.xml

notifications:
  on_success: always
  on_failure: always
