<div class="form-actions">
    <footer>
        <div class="row">
            <div class="col-md-12">
                <a href="<?php echo $resetUrl; ?>" class="btn btn-default" type="submit">
                    Cancelar
                </a>
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-save"></i>
                    <?php echo $submitText; ?>
                </button>
            </div>
        </div>
    </footer>
</div>